export default {
    HEADER: 'Gautham Krishna',
    TITLE: 'I create artisan digital experiences.',
    SUBTITLE: 'I also care about how it feels, not just how it works.',
    COMPANY: 'Adobe',
    COMPANY_URL: 'https://www.adobe.com',
    LOCATION: `12°58′44″N 77°35′30″E`,
    ABOUT_TAG: 'Developer | Designer',
    ABOUT_TEXT: 'As a Frontend Engineer at Adobe, I design and build scalable, high-performance web platforms. My work blends modern architecture with a strong sense of visual and interaction design. Every detail is intentional, engineered for clarity, speed, and lasting impact.',
    WORK_HEADING: 'Portfolio',
    SOCIAL_LINK1_TEXT: 'LinkedIn',
    SOCIAL_LINK1_URL: 'https://www.linkedin.com/in/gauthamkrishnas/',
    SOCIAL_LINK2_TEXT: 'GitHub',
    SOCIAL_LINK2_URL: 'https://github.com/gauthamkrishnax',
    SOCIAL_LINK3_TEXT: 'Instagram',
    SOCIAL_LINK3_URL: 'https://www.instagram.com/2boddah/',
    SOCIAL_LINK4_TEXT: 'Behance',
    SOCIAL_LINK4_URL: 'https://www.behance.net/gauthamkrishnax',
    FOOTER_TEXT: '© 2026 Gautham Krishna. All rights reserved.',
}