export default function template(project) {
    return `
    {{! Project Page for ${project.name} }}
    {{! DO NOT EDIT THIS FILE DIRECTLY. }}
    {{! USE src/projects/template.js instead. }}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${project.name} | Gautham Krishna</title>
        <link rel="stylesheet" href="/src/styles/style.css">
    </head>
    <body class="project">
        {{> header }}
        <main>
            {{> ${project.id} }}
        </main>
        {{> footer }}
    </body>
    </html>
    `
}